# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/account.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(700, 55)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(-1, 10, 691, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.service = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.service.setObjectName("service")
        self.horizontalLayout.addWidget(self.service)
        self.username = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.username.setObjectName("username")
        self.horizontalLayout.addWidget(self.username)
        self.password = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.password.setReadOnly(True)
        self.password.setObjectName("password")
        self.horizontalLayout.addWidget(self.password)
        self.viewButton = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        self.viewButton.setObjectName("viewButton")
        self.horizontalLayout.addWidget(self.viewButton)
        self.deleteButton = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        self.deleteButton.setObjectName("deleteButton")
        self.horizontalLayout.addWidget(self.deleteButton)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.service.setText(_translate("Form", "TextLabel"))
        self.username.setText(_translate("Form", "TextLabel"))
        self.viewButton.setText(_translate("Form", "View"))
        self.deleteButton.setText(_translate("Form", "Delete"))
