# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/add_account.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class AddAccountUi(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 420, 781, 171))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.service = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.service.setObjectName("service")
        self.verticalLayout.addWidget(self.service)
        self.username = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.username.setObjectName("username")
        self.verticalLayout.addWidget(self.username)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.password = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.horizontalLayout.addWidget(self.password)
        self.veiwButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        icon = QtGui.QIcon.fromTheme("edit-find")
        self.veiwButton.setIcon(icon)
        self.veiwButton.setObjectName("veiwButton")
        self.horizontalLayout.addWidget(self.veiwButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.addButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.addButton.setObjectName("addButton")
        self.verticalLayout.addWidget(self.addButton)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(225, 180, 331, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.backButton = QtWidgets.QPushButton(Form)
        self.backButton.setGeometry(QtCore.QRect(20, 0, 191, 41))
        icon = QtGui.QIcon.fromTheme("go-previous")
        self.backButton.setIcon(icon)
        self.backButton.setObjectName("backButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.service.setPlaceholderText(_translate("Form", "Service"))
        self.username.setPlaceholderText(_translate("Form", "User name"))
        self.password.setPlaceholderText(_translate("Form", "Password"))
        self.veiwButton.setText(_translate("Form", "View"))
        self.addButton.setText(_translate("Form", "Add Account"))
        self.label.setText(_translate("Form", "Add Account"))
        self.backButton.setText(_translate("Form", "Back"))
