# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/create_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class CreateUserUi(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 350, 781, 131))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.Container = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.Container.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.Container.setContentsMargins(0, 0, 0, 0)
        self.Container.setObjectName("Container")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.name = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.name.setObjectName("name")
        self.verticalLayout.addWidget(self.name)
        self.username = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.username.setObjectName("username")
        self.verticalLayout.addWidget(self.username)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.password = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.horizontalLayout.addWidget(self.password)
        self.viewButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        icon = QtGui.QIcon.fromTheme("edit-find")
        self.viewButton.setIcon(icon)
        self.viewButton.setObjectName("viewButton")
        self.horizontalLayout.addWidget(self.viewButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.createUser = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.createUser.setObjectName("createUser")
        self.verticalLayout.addWidget(self.createUser)
        self.Container.addLayout(self.verticalLayout)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 70, 779, 137))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.backButton = QtWidgets.QPushButton(Form)
        self.backButton.setGeometry(QtCore.QRect(0, 0, 131, 41))
        icon = QtGui.QIcon.fromTheme("go-previous")
        self.backButton.setIcon(icon)
        self.backButton.setObjectName("backButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.name.setPlaceholderText(_translate("Form", "Name"))
        self.username.setPlaceholderText(_translate("Form", "User name"))
        self.password.setPlaceholderText(_translate("Form", "Password"))
        self.viewButton.setText(_translate("Form", "View"))
        self.createUser.setText(_translate("Form", "Create User"))
        self.label.setText(_translate("Form", "Create User"))
        self.backButton.setText(_translate("Form", "Back"))
