# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/home.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class HomeUi(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, -10, 791, 531))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.container = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.container.setContentsMargins(0, 0, 0, 0)
        self.container.setObjectName("container")
        self.welcome = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.welcome.setFont(font)
        self.welcome.setAlignment(QtCore.Qt.AlignCenter)
        self.welcome.setObjectName("welcome")
        self.container.addWidget(self.welcome, 1, 0, 1, 1)
        self.passwordHolder = QtWidgets.QScrollArea(self.gridLayoutWidget)
        self.passwordHolder.setWidgetResizable(True)
        self.passwordHolder.setObjectName("passwordHolder")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 787, 466))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.passwordHolder.setWidget(self.scrollAreaWidgetContents)
        self.container.addWidget(self.passwordHolder, 2, 0, 1, 1)
        self.addButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.addButton.setObjectName("addButton")
        self.container.addWidget(self.addButton, 3, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.welcome.setText(_translate("Form", "Hello"))
        self.addButton.setText(_translate("Form", "Add Account"))
