# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class LoginUi(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 781, 581))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.container = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.container.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.container.setContentsMargins(0, 0, 0, 0)
        self.container.setObjectName("container")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.container.addWidget(self.label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.username = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.username.setObjectName("username")
        self.verticalLayout.addWidget(self.username)
        self.password = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.password.setObjectName("password")
        self.verticalLayout.addWidget(self.password)
        self.login = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.login.setObjectName("login")
        self.verticalLayout.addWidget(self.login)
        self.createUser = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.createUser.setObjectName("createUser")
        self.verticalLayout.addWidget(self.createUser)
        self.container.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "PassKeeper"))
        self.username.setPlaceholderText(_translate("Form", "User name"))
        self.password.setPlaceholderText(_translate("Form", "Password"))
        self.login.setText(_translate("Form", "Login"))
        self.createUser.setText(_translate("Form", "Create User"))
